pass URL params to filter results
windward-ltd/ww-embedded-app pull request #1
Opened 2023-07-03 15:02 UTC by stellaanaviW

2023-07-03 15:18 UTC, ronfogel requested changes

2023-07-03 15:18 UTC, ronfogel commented on src/pages/index.tsx
> +    const filters = filtersMap['Tracking completed'];
why?

2023-07-03 15:18 UTC, ronfogel commented on src/pages/index.tsx
> +    const urlParams = searchTermsParam && filtersParam ? searchTermsParam + AMPERSAND_URL + filtersParam : searchTermsParam || filtersParam;
you can do that, and remove all the other related code

`const urlParams = new URLSearchParams({ filters, searchTerms }).toString();`

2023-07-03 15:18 UTC, ronfogel commented on src/pages/index.tsx
> +                    src={`${process.env.NEXT_PUBLIC_EMBEDDED_APP_SCRIPT_ORIGIN}/embed.min.js${urlParams? QUESTION_MARK + urlParams: ''}`}></Script>
it's OK to have question mark without anything after that.

```
<Script data-id={WINDWARD_EMBEDDED_SCRIPT_ID}
                    src={`${process.env.NEXT_PUBLIC_EMBEDDED_APP_SCRIPT_ORIGIN}/embed.min.js?${urlParams}`}></Script>
```

2023-07-03 15:19 UTC, stellaanaviW commented on src/pages/index.tsx
> +    const filters = filtersMap['Tracking completed'];
by mistake, it should be commented out (probably left from my tests)

2023-07-03 15:20 UTC, stellaanaviW commented on src/pages/index.tsx
> +    const urlParams = searchTermsParam && filtersParam ? searchTermsParam + AMPERSAND_URL + filtersParam : searchTermsParam || filtersParam;
cool

2023-07-04 07:38 UTC, ronfogel requested changes

2023-07-04 07:38 UTC, ronfogel commented on src/pages/index.tsx
> +    const urlParams = filters && searchTerms ? new URLSearchParams({ filters, searchTerms})
why all this mess?
`const urlParams = new URLSearchParams(omitBy({ filters, searchTerms }, isEmpty)).toString();`

the above should work. install `lodash` as dependency and probably `@types/lodash` as dev dependency for the typescript

2023-07-04 07:38 UTC, ronfogel commented on src/pages/index.tsx
> +    const filters = ''; // filtersMap['Tracking completed'];
I would remove it, it's not needed.
Instead, I would use the `context` parameter from `getServerSideProps` to get the filters/searchTerms from the url itself and pass it to the component.

```
export async function getServerSideProps({ query }) {
...

const { searchTerms = '', filters = '' } = query ?? {};

return {
        props: {code, searchTerms, filters}
    }
```

this way, you can add the parameters to the url which will pass it down
http://localhost:3000/?searchTerms=something&....

2023-07-04 07:42 UTC, stellaanaviW commented on .env
> +EMBEDDED_APP_SCRIPT_CLIENT_SECRET=2e15a83702ccc00bce09dce494e374cf3df2fc841188b4a8
by mistake

2023-07-04 07:43 UTC, stellaanaviW commented on src/pages/index.tsx
> +    const filters = ''; // filtersMap['Tracking completed'];
nice

2023-07-04 11:59 UTC, ronfogel approved these changes

2023-07-04 12:00 UTC, merged